// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return iOS;
      case TargetPlatform.macOS:
        return iOS;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCbuh8WLUxN-SQfqhEG_YHIg6QlYaNFNv0",
    authDomain: "vatsalyaclinicproject.firebaseapp.com",
    projectId: "vatsalyaclinicproject",
    storageBucket: "vatsalyaclinicproject.firebasestorage.app",
    messagingSenderId: "846259022190",
    appId: "1:846259022190:web:8c14c31a9bf7ef3b17b97f",
    measurementId: "G-VLJ54FJDEV"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCbuh8WLUxN-SQfqhEG_YHIg6QlYaNFNv0",
    appId: '1:846259022190:android:18ddb8654bd3fbaa17b97f',
    projectId: "vatsalyaclinicproject",
    storageBucket: "vatsalyaclinicproject.firebasestorage.app",
    messagingSenderId: "846259022190",
    measurementId: "G-VLJ54FJDEV"
  );

  static const FirebaseOptions iOS = FirebaseOptions(
      apiKey: "AIzaSyCbuh8WLUxN-SQfqhEG_YHIg6QlYaNFNv0",
      appId: '1:846259022190:ios:be59bf7eda7a884117b97f',
      projectId: "vatsalyaclinicproject",
      storageBucket: "vatsalyaclinicproject.firebasestorage.app",
      messagingSenderId: "846259022190",
      measurementId: "G-VLJ54FJDEV"
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyCbuh8WLUxN-SQfqhEG_YHIg6QlYaNFNv0",
    authDomain: "vatsalyaclinicproject.firebaseapp.com",
    projectId: "vatsalyaclinicproject",
    storageBucket: "vatsalyaclinicproject.firebasestorage.app",
    messagingSenderId: "846259022190",
    appId: "1:846259022190:web:8c14c31a9bf7ef3b17b97f",
    measurementId: "G-VLJ54FJDEV"
  );
}
